# Generated by Django 5.2.15 on 2026-06-17 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='category',
        ),
    ]
