# Generated by Django 5.2.15 on 2026-06-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_remove_complaint_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='reference_number',
            field=models.CharField(editable=False, max_length=30, unique=True),
        ),
    ]
