# Generated by Django 5.2.15 on 2026-06-19 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_alter_complaint_complainant_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='idempotency_key',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
